[package]
name = "handler_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
inventory = "0.3.20"
convert_case = "0.8.0"